#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     LightFloorSensor, sensorLightActive)
#pragma config(Sensor, S3,     PegSonar,       sensorSONAR)
#pragma config(Sensor, S4,     AccordianSonar, sensorSONAR)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     LeftWheel,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     AccordionTop,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     AccordionBottom, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     RightWheel,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// The "master override" swtich
#define        MATCH_BUILD  0

#define    TESTING_SENSORS  1
#define TESTING_AUTONOMOUS  0
#define     TESTING_TELEOP  1
#define    DRIVING_ENABLED  1
#define  ACCORDION_ENABLED  1

// NOTE: Include EVERYTHING before Joystick.h
#include "JoystickDriver.c"
#include "Motor.h"
#include "Sonar.h"
#include "Accordion.h"
#include "Joystick.h"

void initRobot()
{
    initMotors(LeftWheel, RightWheel);
    initAccordion(AccordionBottom, AccordionTop);
    initSonars(PegSonar, AccordianSonar, LightFloorSensor);
}

void sensorDebug() {
	while (true) {
		writeDebugStreamLine("Light sensor: %i", LightFloorSensor);
		wait1Msec(100);
	}
}

task main()
{
	initRobot();
	waitForStart();

	if (TESTING_SENSORS && !MATCH_BUILD) {
		sensorDebug();
	} else {
		startMatch();
	}
}
