#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     sonar,          sensorSONAR)
#pragma config(Sensor, S3,     magnetic,       sensorHiTechnicMagnetic)
#pragma config(Motor,  motorA,          leftArm,       tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          rightArm,      tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     RightWheel,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     LeftWheel,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     LiftController, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messssensor
//#include "HTMAG-driver.h"

void initializeRobot()
{
	// Place code here to initialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
	return;
}

void joystickDebug()
{
	eraseDisplay();
	nxtDisplayTextLine(0, "Joystick 1: (%i,%i)", joystick.joy1_x1, joystick.joy1_y1);
	nxtDisplayTextLine(1, "Joystick 2: (%i,%i)", joystick.joy1_x2, joystick.joy1_y2);
	nxtDisplayTextLine(2, "Top Hat: %i", joystick.joy1_TopHat);
	nxtDisplayTextLine(3, "Buttons: 1:%i 2:%i 3:%i 4:%i 5:%i", joy1Btn(1), joy1Btn(2), joy1Btn(3), joy1Btn(4), joy1Btn(5));
	nxtDisplayTextLine(4, "Buttons: 6:%i 7:%i 8:%i 9:%i 10:%i", joy1Btn(6), joy1Btn(7), joy1Btn(8), joy1Btn(9), joy1Btn(10));
	nxtDisplayTextLine(5, "Motors: L:%i R:%i", motor[LeftWheel], motor[RightWheel]);
	nxtDisplayTextLine(6, "Distance: %i", SensorValue(2));
	nxtDisplayTextLine(7, "Battery: %i (NXT: %i)", externalBattery, nAvgBatteryLevel);
}

int convertJoystickToMotor(const int power)
{
	return ((power * 100) / 127);
}

int convertJoystickToMotorAvg(const int x, const int y)
{
	return ((((x + y) / 2) * 100) / 127);
}

int setDeadZone(const int Value)
{
	if(Value < -15 || Value > 15) return Value;
	else return 0;
}

task main()
{

	/*
	while(true)
	{
	motor[motorB] = 10;
	wait1Msec(1000);
	motor[motorA] = 10;
	wait1Msec(1000);
	}
	*/
	initializeRobot();

	waitForStart();   // wait for start of tele-op phase

	while(true)
	{
		getJoystickSettings(joystick);

		motor[LeftWheel] = convertJoystickToMotor(setDeadZone((int)joystick.joy1_y1));
		motor[RightWheel] = convertJoystickToMotor(setDeadZone((int)joystick.joy1_y2));
		motor[LiftController] = 0;

		if(joy1Btn(1)) motor[LiftController] = 15;
		if(joy1Btn(3)) motor[LiftController] = -15;


		//joystickDebug();
	}
}
